#ifndef __CONFIG_H__
#define __CONFIG_H__

// ###################################################################### //
// ## For board specific GPIO-PIN definition please see platformio.ini ## //
// ###################################################################### //

#define SOFTWARE_VERSION_MAJOR 1
#define SOFTWARE_VERSION_MINOR 0
#define SOFTWARE_VERSION_PATCH 0
#define HARDWARE_VERSION_MAJOR 3
#define HARDWARE_VERSION_MINOR 1

#define VESC_CAN_ID 25 // VESC-ID as configured in VESC as decimal
#define BATTERY_CELL_COUNT 20
#define BATTERY_MIN_VOLTAGE 60
#define BATTERY_MAX_VOLTAGE 84
// #define FAKE_VESC_ENABLED

#define LIGHT_NUMPIXELS 42 // the number of LEDs (first half front, second half back, needs to be even number)
#define LIGHT_LED_TYPE NEO_GRBW + NEO_KHZ800

#define LIGHT_MAX_BRIGHTNESS 255
#define LIGHT_MAX_BRIGHTNESS_BRAKE 50
#define LIGHT_PRIMARY_COLOR_RED 255
#define LIGHT_PRIMARY_COLOR_GREEN 255
#define LIGHT_PRIMARY_COLOR_BLUE 255
#define LIGHT_PRIMARY_COLOR_WHITE 255
#define LIGHT_SECONDARY_COLOR_RED 255
#define LIGHT_SECONDARY_COLOR_GREEN 0
#define LIGHT_SECONDARY_COLOR_BLUE 0
#define LIGHT_SECONDARY_COLOR_WHITE 50
#define LIGHT_START_DURATION 3000
#define LIGHT_START_PATTERN Pattern::SLIDE
#define LIGHT_IDLE_TIMEOUT 120000
#define LIGHT_IDLE_PATTERN Pattern::PULSE

#define LIGHT_BAR_ENABLED      // activates a light bar
#define LIGHT_BAR_NUMPIXELS 10 // the number of LEDS of the battery bar
// Which LEDs represent which values
#define LIGHT_BAR_LED_INDEX_ADC1 {8,9}
#define LIGHT_BAR_LED_INDEX_ADC2 {0,1}
#define LIGHT_BAR_LED_INDEX_BATTERY_CHARGE {2,3,6,7}
#define LIGHT_BAR_LED_INDEX_DUTY_CYCLE {4,5}
// Config options
#define LIGHT_BAR_OFF_ERPM 10000
// Color Options
#define LIGHT_BAR_ADC_ON_COLOR_RED 0
#define LIGHT_BAR_ADC_ON_COLOR_GREEN 0
#define LIGHT_BAR_ADC_ON_COLOR_BLUE 100
#define LIGHT_BAR_ADC_ON_COLOR_WHITE 0
#define LIGHT_BAR_ADC_OFF_COLOR_RED 100
#define LIGHT_BAR_ADC_OFF_COLOR_GREEN 0
#define LIGHT_BAR_ADC_OFF_COLOR_BLUE 100
#define LIGHT_BAR_ADC_OFF_COLOR_WHITE 0
#define LIGHT_BAR_BATTERY_CHARGE_LOW_COLOR_RED 255
#define LIGHT_BAR_BATTERY_CHARGE_LOW_COLOR_GREEN 0
#define LIGHT_BAR_BATTERY_CHARGE_LOW_COLOR_BLUE 0
#define LIGHT_BAR_BATTERY_CHARGE_LOW_COLOR_WHITE 50
#define LIGHT_BAR_BATTERY_CHARGE_HIGH_COLOR_RED 0
#define LIGHT_BAR_BATTERY_CHARGE_HIGH_COLOR_GREEN 20
#define LIGHT_BAR_BATTERY_CHARGE_HIGH_COLOR_BLUE 0
#define LIGHT_BAR_BATTERY_CHARGE_HIGH_COLOR_WHITE 0
#define LIGHT_BAR_DUTY_CYCLE_LOW_COLOR_RED 0
#define LIGHT_BAR_DUTY_CYCLE_LOW_COLOR_GREEN 20
#define LIGHT_BAR_DUTY_CYCLE_LOW_COLOR_BLUE 0
#define LIGHT_BAR_DUTY_CYCLE_LOW_COLOR_WHITE 0
#define LIGHT_BAR_DUTY_CYCLE_HIGH_COLOR_RED 255
#define LIGHT_BAR_DUTY_CYCLE_HIGH_COLOR_GREEN 0
#define LIGHT_BAR_DUTY_CYCLE_HIGH_COLOR_BLUE 0
#define LIGHT_BAR_DUTY_CYCLE_HIGH_COLOR_WHITE 50

#endif //__CONFIG_H__
